name: 🐛 Bug
description: Report an issue to help improve the project.
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A brief description of the issue or question
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: Please add screenshots if applicable
    validations:
      required: false
  - type: textarea
    id: extrainfo
    attributes:
      label: Additional information
      description: Is there anything else we should know about this bug?
    validations:
      required: false
